// <auto-generated />
namespace MortgageApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDues));
        
        string IMigrationMetadata.Id
        {
            get { return "201308291424095_AddDues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
