// <auto-generated />
namespace MortgageApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPmi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPmi));
        
        string IMigrationMetadata.Id
        {
            get { return "201308291420563_AddPmi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
